### ISSUE TITLE
Add options to throw exceptions or expose problems found as Clojure data structures

### ISSUE THREAD

**Issue by eigenhombre** [tolitius/boot-check#6] opened 2016-12-13 17:46 UTC
My team would like to fail our builds depending on linting output, which is impossible to do without parsing the output from the linting tasks (yagni, bikeshed, etc).

It would be helpful to allow the option to raise an exception or, perhaps better yet, expose the problems found as Clojure data structures so that a wrapper task could fail drastically when problems occur.

As it is we are having to dissect and reimplement portions of the library to get the desired behavior (or parse the output as strings).

**Comment by tolitius** [comment] 2016-12-13 20:49
The problem is some of the projects.

For example Bikeshed, does not return anything besides `true` or `false`. That is true for its internal tasks as well.

For Eastwood, it does not return actuals but rather the counters, etc..

I added the `--throw-on-errors` on every task. It is in `0.1.4-SNAPSHOT`.
Check out the [handling errors](https://github.com/tolitius/boot-check#handling-errors) docs.

Let me know if it works for you.

**Comment by eigenhombre** [comment] 2016-12-13 22:00
Thanks! Next time I'm getting my hands dirty with this I can try it out.  Seems close-able for now, but will let you close the issue. Thanks again for the quick response.

**Comment by tolitius** [comment] 2017-04-07 05:54
closing this. feel free to reopen if you have more questions.

**Closed as completed by tolitius** 2017-04-07 05:54 UTC
