### ISSUE TITLE
Disable generation of txt files

### ISSUE THREAD

**Issue by binarykitchen** [tolitius/boot-check#20] opened 2018-07-05 03:37 UTC
I can see these temporary txt files in the root folder

forms-analyzed.txt
forms-emitted.txt
forms-read.txt

How can I configure boot-check not to generate these or at least clean them up afterwards?

**Comment by voytech** [comment] 2018-07-05 22:49
It is not configurable right now. Removing these files requires introducing fix in function calling internal checker - I think eastwood. I will fix that in the very nearest future ( one of my recent commits introduced this unwanted behaviour :( )

**Comment by voytech** [comment] 2018-07-05 22:53
Duplicate of #19

**Comment by tolitius** [comment] 2018-08-12 18:01
fixed by #21

**Closed as completed by tolitius** 2018-08-12 18:01 UTC
